config/routes.rb
Rails.application.routes.draw do
  get "home/about", to: "homes#about", as: :homes_about
  get "users/show"
  devise_for :users
  root to: "homes#top"
  resources :books, only: [:create, :index, :show, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :users, only: [:create, :index, :show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  attachment :profile_image
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  validates :title, presence: true

  validates :body,
    presence: true,
    length: {maximum: 200 }

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates_uniqueness_of :book_id, scope: :user_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  attachment :profile_image

  validates :name, presence: true,
    uniqueness: true,
    length: { in: 2..20 }

  validates :introduction, length: { maximum: 50 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top, :about]
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(resource)
  end




  protected

  def configure_permitted_parameters
    added_attrs = [:name, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end

end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    comment.save
    redirect_to book_path(book)
  end

  def destroy
    BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
    redirect_back(fallback_location: root_path)
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def create
    @books = Book.all
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    @user = current_user
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book)
    else
      render :index
    end
  end

  def index
    @user = current_user
    @book = Book.new
    @books = Book.all
  end

  def show
    @book_new = Book.new
    @book_comment = BookComment.new
    @book = Book.find(params[:id])
    @user = @book.user
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render :edit
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.delete
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body, :user_id)
  end

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_back(fallback_location: root_path)
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :authenticate_user!
  def index
    @book = Book.new
    @user = current_user
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books.all
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render :edit
    else
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_sidebar.html.erb
<h1 class="mt-5">New book</h1>
<%= form_with model: book, local: true do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Opinion</h4>
  <%= f.text_field :body %></br>
  <%= f.submit "Create Book" , class: "my-2 btn btn-success"  %>
<% end %>

app/views/books/edit.html.erb
<div class="container mx-auto my-3" style="width: 200px;">
  <h2 class="row">Editing Book</h2>
  <% if @book.errors.any? %>
  　　<%= @book.errors.count %>error prohibited this obj from being saved:
  　<% @book.errors.full_messages.each do |book| %>
  　　  <%= book %>
    <% end %>
　<% end %>
  <%= form_with model:@book, local:true do |f| %>
    <label class="row">Title</label>
    <label class="row">
      <%= f.text_field :title, autofocus: true, id:"inputName"%>
    </label>
    <label class="row">Opinion</label>
    <label class="row">
      <%= f.text_field :body, autofocus: true, id:"inputName"%>
    </label>
    <label class="row">
      <%= f.submit "Update Book" , class: "my-2 btn btn-success"  %>
    </label>
  <% end %>
  <label class="row">
    <%= link_to "Show", book_path(@book.id) %>
    <div class="mx-1">|</div>
    <%= link_to "Back", books_path %>
  </label>
</div>

app/views/books/index.html.erb
<p id="notice"></p>
<% if @book.errors.any? %>
  <%= @book.errors.count %>error prohibited this obj from being saved:
  <% @book.errors.full_messages.each do |book| %>
    <%= book %>
  <% end %>
<% end %>
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render "users/my", user: @user %>
      <%= render "books/sidebar", book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-striped">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
          </tr>
        </thead>
        
        
        
        
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td><%= link_to attachment_image_tag(book.user, :profile_image, size: "40x40", format: 'jpeg', fallback: "no_image.jpg"),user_path(book.user) %></td>
              <td>
                <%= link_to book_path(book.id) do %>
                  <%= book.title %>
                <% end %>
              </td>
              <td><%= book.body %></td>
              <td>
                <% if book.favorited_by?(current_user) %>
                  <%= link_to book_favorites_path(book), method: :delete do %>
                    <div class="text-danger">
                      <i class="fas fa-heart"></i><%= book.favorites.count %>
                    </div>
                  <% end %>
                <% else %>
                  <%= link_to book_favorites_path(book), method: :post do %>
                    <div class="text-primary">
                      <i class="fas fa-heart"></i><%= book.favorites.count %>
                    </div>
                  <% end %>
                <% end %>
              </td>
              <td>コメント数：<%= book.book_comments.count %></td>
            </tr>
          <% end %>
        </tbody>
        
        
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<p id="notice"></p>
<% if flash[:notice] %>
　　<%= flash[:notice] %>
<% end %>
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render "users/my", user: @user %>
      <%= render "books/sidebar", book: @book_new %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>



      <table class="table table-striped">
        <tbody>
          <tr>
            <td>
              <%= link_to attachment_image_tag(@book.user, :profile_image, size: "40x40", format: 'jpeg', fallback: "no_image.jpg"),user_path(@user.id) %>
              <%= link_to user_path(@user.id) do %>
                <%= @user.name %>
              <% end %>
            </td>
            <td>
              <%= link_to book_path(@book.id) do %>
                <%= @book.title %>
              <% end %>
            </td>
            <td><%= @book.body %></td>
            <td>
              <% if @book.favorited_by?(current_user) %>
                <%= link_to book_favorites_path(@book), method: :delete do %>
                  <div class="text-danger">
                    <i class="fas fa-heart"></i><%= @book.favorites.count %>
                  </div>
                <% end %>
              <% else %>
                <%= link_to book_favorites_path(@book), method: :post do %>
                  <div class="text-primary">
                    <i class="fas fa-heart"></i><%= @book.favorites.count %>
                  </div>
                <% end %>
              <% end %>
            </td>
            <td>コメント数：<%= @book.book_comments.count %></td>
            <td>
              <% if @book.user == current_user %>
                <%= link_to edit_book_path(@book) do %>
                  <button type="button" class="ml-2 btn btn-success">
                    Edit
                  </button>
                <% end %>
                <%= link_to book_path(@book), method: :delete do %>
                  <button type="button" class="ml-2 btn btn-danger">
                    Destroy
                  </button>
                <% end %>
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>

      <table class="table table-striped">
        <tbody>
          <% @book.book_comments.each do |book_comment| %>
            <tr>
              <td><%= link_to attachment_image_tag(@book.user, :profile_image, size: "40x40", format: 'jpeg', fallback: "no_image.jpg"),user_path(@user.id) %></td>

              <td>
                <%= link_to user_path(book_comment.user.id) do %>
                  <%= book_comment.user.name %>
                <% end %>
              </td>

              <td><%= book_comment.comment %></td>
              <td>
                <% if book_comment.user == current_user %>
                  <%= link_to book_book_comment_path(book_comment.book, book_comment), method: :delete do %>
                    <button type="button" class="ml-5 btn btn-danger">
                      Destroy
                    </button>
                  <% end %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>


      <div class="new-comment">
        <%= form_with(model:[@book, @book_comment], local: true) do |f| %>
          <%= f.text_area :comment, size: "90x5" %></br>
          <%= f.submit "送信" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<main>
  <p id="notice"></p>
  <div class="mx-auto" style="width: 40%;">
    <h1 class="font-weight-bold">
      welcome to
      <i class="fas fa-book"></i>
      Bookers !!
    </h1>
  </div>
</main>

app/views/homes/top.html.erb
<body>
  <header></header>
  <main>
    <% if flash[:notice] %>
　　  <%= flash[:notice] %>
    <% end %>
    <p id="notice"></p>
    <div class="mx-auto" style="width: 40%;">
      <h1 class="font-weight-bold">
        welcome to
        <i class="fas fa-book"></i>
        Bookers !!
        </h1>
      <p>
        In
        <i class="fas fa-book"></i>
        Bookers,
      </p>
      <p>you can share and exchange your opinions , inpressions , and emotions</p>
      <p>about various books!</p>
      <div class="center">
        <button type="button" class="p-3 mb-4 badge badge-info text-white text-center" style= "width: 80%;">
          <%= link_to "Log in", new_user_session_path %>
        </button>
        <button type="button" class="p-3 mb-4 badge badge-success text-white text-center" style= "width: 80%;">
          <%= link_to  "Sign Up", new_user_registration_path %>
        </button>
      </div>
    </div>
  </main>
  <footer></footer>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css" integrity="sha384-SZXxX4whJ79/gErwcOYf+zWLeJdY/qpuqC4cAa9rOGUstPomtqpuNWT9wdPEn2fk" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body class="d-flex flex-column vh-100">
    <header class="bg-dark">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <a class="navbar-brand text-white" href="/">Bookers</a>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to "Home", user_path(current_user.id), class: "fas fa-home nav-link text-white" %>
            </li>
            <li class="nav-item">
              <%= link_to "Users", users_path, class: "fas fa-users nav-link text-white" %>
            </li>
            <li class="nav-item">
              <%= link_to "Books", books_path, class: "fas fa-book-open nav-link text-white" %>
            </li>
            <li class="nav-item">
              <%= link_to "logout", destroy_user_session_path, method: :delete, class: "fas fa-sign-out-alt nav-link text-white" %>
            </li>
            <% else %>
            <li class="nav-item">
              <%= link_to "Home", root_path, class: "fas fa-home nav-link text-white" %>
            </li>
            <li class="nav-item">
              <%= link_to "About", homes_about_path, class: "fas fa-link nav-link text-white" %>
            </li>
            <li class="nav-item">
              <%= link_to "sign up", new_user_registration_path, class: "fas fa-user-plus nav-link text-white" %>
            </li>
            <li class="nav-item">
              <%= link_to "login", new_user_session_path, class: "fas fa-sign-in-alt nav-link text-white" %>
            </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main class="mb-auto">
    <%= yield %>
    </main>
    <footer class="shadow-sm text-center">
      <p>CopyRight Infratop.inc</p>
    </footer>
  </body>

</html>

app/views/users/_my.html.erb
  <body class="container">
    <h2>User info</h2>
    <div class="profile-container">
      <%= attachment_image_tag user, :profile_image, :fill, 20, 20, format: 'jpeg', fallback: "no_image.jpg" %>
      <div class="row">
        <p class="col text-left">name</p>
        <p class="col"><%= user.name %></p>
      </div>
      <div class="row">
        <p class="col text-left">introduction</p>
        <p class="col"><%= user.introduction %></p>
      </div>
      <%= link_to edit_user_path(user) do %>
        <button type="button" class="btn btn-outline-dark" style="width: 80%;">
          <i class="fas fa-user-cog"></i>
        </button>
      <% end %>
    </div>
  </body>

app/views/users/edit.html.erb
<div class="container">
  <h2 class="row">User info</h2>
  <% if @user.errors.any? %>
    <%= @user.errors.count %>error prohibited this obj from being saved:
      <% @user.errors.full_messages.each do |user| %>
        <%= user %>
      <% end %>
    <% end %>
  <%= form_with model:@user, local:true do |f| %>
    <label class="row">Name</label>
    <label class="row">
      <%= f.text_field :name, autofocus: true, id:"inputName"%>
    </label>
    <label class="row">Image</label>
    <label class="row">
      <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
    </label>
    <label class="row">Introduction</label>
    <label class="row">
      <%= f.text_field :introduction, autofocus: true, id:"inputName"%>
    </label>
    <%= f.submit "Update User" , class: "my-2 btn btn-success"  %>
  <% end %>
</div>

app/views/users/index.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render "users/my", user: @user %>
      <%= render "books/sidebar", book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table table-striped">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= attachment_image_tag user, :profile_image, size: "40x40", format: 'jpeg', fallback: "no_image.jpg" %></td>
              <td><%= user.name %></td>
              <td><%= link_to "Show", user_path(user.id) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<p id="notice"></p>
<% if flash[:notice] %>
　　<%= flash[:notice] %>
<% end %>
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render "users/my", user: @user %>
      <%= render "books/sidebar", book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-striped">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td><%= link_to attachment_image_tag(book.user, :profile_image, size: "40x40", format: 'jpeg', fallback: "no_image.jpg"),user_path(@user.id) %></td>
              <td>
                <%= link_to book_path(book.id) do %>
                  <%= book.title %>
                <% end %>
              </td>
              <td><%= book.body %></td>
              <td>
                <% if book.favorited_by?(current_user) %>
                  <%= link_to book_favorites_path(book), method: :delete do %>
                    <div class="text-danger">
                      <i class="fas fa-heart"></i><%= book.favorites.count %>
                    </div>
                  <% end %>
                <% else %>
                  <%= link_to book_favorites_path(book), method: :post do %>
                    <div class="text-primary">
                      <i class="fas fa-heart"></i><%= book.favorites.count %>
                    </div>
                  <% end %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>